#!/usr/bin/env node

const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

// --- COLORS & HELPERS ---
const colors = {
    reset: "\x1b[0m",
    bold: "\x1b[1m",
    green: "\x1b[32m",
    blue: "\x1b[34m",
    yellow: "\x1b[33m",
    red: "\x1b[31m",
    cyan: "\x1b[36m",
    magenta: "\x1b[35m"
};

function log(msg, color = colors.reset) {
    console.log(`${color}${msg}${colors.reset}`);
}

function run(command, cwd = process.cwd()) {
    try {
        execSync(command, { stdio: 'inherit', cwd });
    } catch (error) {
        log(`\n❌ Error while executing: ${command}`, colors.red);
        log("Please check the terminal output above to see what went wrong.", colors.yellow);
        process.exit(1);
    }
}

function spinnerCheck(msg) {
    process.stdout.write(`${colors.cyan}➤${colors.reset} ${msg}... `);
    return function done() {
        console.log(`${colors.green}✓ Done${colors.reset}`);
    };
}

// --- MAIN INSTALLATION FLOW ---
async function main() {
    console.clear();
    log("==================================================", colors.cyan);
    log("     🚀 PULSE ENTERPRISE UPTIME MONITOR 🚀        ", colors.bold + colors.green);
    log("==================================================", colors.cyan);
    console.log();
    log("Starting automated installation process...", colors.yellow);
    console.log();

    // 1. Check Node.js Version
    const nodeMajor = process.versions.node.split('.')[0];
    if (parseInt(nodeMajor) < 18) {
        log(`❌ Node.js 18 or higher is required! You are using v${process.versions.node}`, colors.red);
        process.exit(1);
    }

    // 2. Clone repository if not already in one
    const isGitRepo = fs.existsSync(path.join(process.cwd(), '.git'));
    const isPulseDir = fs.existsSync(path.join(process.cwd(), 'package.json')) &&
        fs.readFileSync(path.join(process.cwd(), 'package.json'), 'utf-8').includes('"name": "uptime-monitor"');

    let installDir = process.cwd();

    if (!isPulseDir) {
        log("Cloning Pulse repository...", colors.blue);
        run('git clone https://github.com/LootingVI/Pulse.git pulse-monitor');
        installDir = path.join(process.cwd(), 'pulse-monitor');
        process.chdir(installDir);
    }

    // 3. Environment Variables
    const envPath = path.join(installDir, '.env');
    if (!fs.existsSync(envPath)) {
        let done = spinnerCheck("Creating .env file");

        // Generate a fast random secure string for NextAuth
        const secret = require('crypto').randomBytes(32).toString('hex');

        const envContent = `
# Automatically generated by install.js
NEXTAUTH_SECRET="${secret}"
NEXTAUTH_URL="http://localhost:3000"
NODE_ENV="production"
`;
        fs.writeFileSync(envPath, envContent.trim());
        done();
    } else {
        log("➤ .env file already exists, skipping creation.", colors.cyan);
    }

    console.log();

    // 4. Install Dependencies
    log("📦 Installing NPM dependencies (this might take a minute)...", colors.blue);
    run('npm install', installDir);
    console.log();

    // 5. Setup Database
    log("🗄️ Setting up SQLite database...", colors.blue);
    run('npx prisma db push --accept-data-loss', installDir);
    run('npx prisma generate', installDir);
    console.log();

    // 6. Build the Application
    log("🏗️ Compiling the Next.js production build...", colors.magenta);
    run('npm run build', installDir);
    console.log();

    log("==================================================", colors.cyan);
    log("              ✅ INSTALLATION COMPLETE!           ", colors.bold + colors.green);
    log("==================================================", colors.cyan);
    console.log();
    log("You can now start Pulse by running:", colors.yellow);
    console.log();
    log("  " + colors.bold + "npm run start" + colors.reset);
    console.log();
    log("Or use a process manager like PM2 to keep it running in the background:", colors.blue);
    log("  " + colors.bold + "npx pm2 start npm --name 'pulse' -- run start" + colors.reset);
    console.log();
    log("After starting, visit " + colors.cyan + "http://localhost:3000" + colors.reset + " in your browser to complete the setup wizard.");
    console.log();
}

main().catch(err => {
    log(`\n❌ Fatal Error: ${err.message}`, colors.red);
    process.exit(1);
});
